description = "The UML OCL for AMF"
name = "matreshka_amf_ocl"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_amf_ocl.gpr"]
tags = ["uml", "meta", "diagram", "ocl"]

[configuration]
disabled = true

[[depends-on]]
matreshka_amf_uml = "22.0.0"
matreshka_league = "22.0.0"

