description = "PostgreSQL binding for Ada"
name = "matreshka_sql_postgresql"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_sql_postgresql.gpr"]
tags = ["sql", "database", "db", "postgresql"]

[configuration]
disabled = true

[[depends-on]]
libpq = "any"
matreshka_league = "22.0.0"

