------------------------------------------------------------------------------
--                                                                          --
--                            Matreshka Project                             --
--                                                                          --
--                          Ada Modeling Framework                          --
--                                                                          --
--                        Runtime Library Component                         --
--                                                                          --
------------------------------------------------------------------------------
--                                                                          --
-- Copyright © 2012, Vadim Godunko <vgodunko@gmail.com>                     --
-- All rights reserved.                                                     --
--                                                                          --
-- Redistribution and use in source and binary forms, with or without       --
-- modification, are permitted provided that the following conditions       --
-- are met:                                                                 --
--                                                                          --
--  * Redistributions of source code must retain the above copyright        --
--    notice, this list of conditions and the following disclaimer.         --
--                                                                          --
--  * Redistributions in binary form must reproduce the above copyright     --
--    notice, this list of conditions and the following disclaimer in the   --
--    documentation and/or other materials provided with the distribution.  --
--                                                                          --
--  * Neither the name of the Vadim Godunko, IE nor the names of its        --
--    contributors may be used to endorse or promote products derived from  --
--    this software without specific prior written permission.              --
--                                                                          --
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS      --
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT        --
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR    --
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT     --
-- HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,   --
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED --
-- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR   --
-- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF   --
-- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING     --
-- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS       --
-- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.             --
--                                                                          --
------------------------------------------------------------------------------
--  $Revision$ $Date$
------------------------------------------------------------------------------
--with AMF.CMOF.Properties;
--with AMF.Internals.Helpers;
--with AMF.Internals.Listener_Registry;
--with AMF.UTP.Holders.Collection_Kinds;

package body AMF.Internals.Tables.UTP_Notification is

--   --------------------------
--   -- Notify_Attribute_Set --
--   --------------------------
--
--   procedure Notify_Attribute_Set
--    (Element   : AMF.Internals.AMF_Element;
--     Property  : AMF.Internals.CMOF_Element;
--     Old_Value : AMF.UTP.UTP_Collection_Kind;
--     New_Value : AMF.UTP.UTP_Collection_Kind) is
--   begin
--      AMF.Internals.Listener_Registry.Notify_Attribute_Set
--       (AMF.Internals.Helpers.To_Element (Element),
--        AMF.CMOF.Properties.CMOF_Property_Access
--         (AMF.Internals.Helpers.To_Element (Property)),
--        (Is_Empty => True),
--        AMF.UTP.Holders.Collection_Kinds.To_Holder (Old_Value),
--        AMF.UTP.Holders.Collection_Kinds.To_Holder (New_Value));
--   end Notify_Attribute_Set;

end AMF.Internals.Tables.UTP_Notification;
