# ARCHITECTURE can be one of: portable_32, portable_64, x86, x86_64
# ARCHITECTURE = portable_32_be
ARCHITECTURE = portable_32_le
# ARCHITECTURE = portable_64_be
# ARCHITECTURE = portable_64_le
# ARCHITECTURE = x86
# ARCHITECTURE = x86_64

# BUILD can be one of: DEBUG, RELEASE
BUILD = RELEASE
# BUILD = DEBUG
