# ARCHITECTURE can be one of: portable_32, portable_64, x86, x86_64
# ARCHITECTURE = portable_32
ARCHITECTURE = portable_64
# ARCHITECTURE = x86
# ARCHITECTURE = x86_64

# BUILD can be one of: DEBUG, RELEASE
BUILD = RELEASE
# BUILD = DEBUG
