--  This program extracts data from the code generated by ayacc, and generates
--  actual implementation of parser for regular expression engine.

with Ada.Wide_Text_IO;

with Asis.Ada_Environments;
with Asis.Compilation_Units;
with Asis.Elements;
with Asis.Implementation;

with Parser_Extractor;
with Parser_Generator;

procedure Parser_Transformer is
   Transformer_Context : Asis.Context;
   Parser_Unit         : Asis.Compilation_Unit;
   Parser_Body         : Asis.Element;

begin
   Asis.Implementation.Initialize ("-asis05");
   Asis.Ada_Environments.Associate (Transformer_Context, "Transformer_Context", "-C1 .gen/regexp_parser.adt");
   Asis.Ada_Environments.Open (Transformer_Context);

   Parser_Unit := Asis.Compilation_Units.Compilation_Unit_Body ("Regexp_Parser", Transformer_Context);
   Parser_Body := Asis.Elements.Unit_Declaration (Parser_Unit);
   Parser_Extractor.Extract (Parser_Body);

   Parser_Unit := Asis.Compilation_Units.Library_Unit_Declaration ("Regexp_Parser.Goto_Table", Transformer_Context);
   Parser_Body := Asis.Elements.Unit_Declaration (Parser_Unit);
   Parser_Extractor.Extract (Parser_Body);

   Parser_Unit := Asis.Compilation_Units.Library_Unit_Declaration ("Regexp_Parser.Shift_Reduce", Transformer_Context);
   Parser_Body := Asis.Elements.Unit_Declaration (Parser_Unit);
   Parser_Extractor.Extract (Parser_Body);

   Parser_Unit := Asis.Compilation_Units.Library_Unit_Declaration ("Regexp_Parser_Tokens", Transformer_Context);
   Parser_Body := Asis.Elements.Unit_Declaration (Parser_Unit);
   Parser_Extractor.Extract (Parser_Body);

   Parser_Generator.Generate_Parser_Tokens;
   Parser_Generator.Generate_Parser_Code;
   Parser_Generator.Generate_Parser_Tables;

   Asis.Ada_Environments.Close (Transformer_Context);
   Asis.Ada_Environments.Dissociate (Transformer_Context);
   Asis.Implementation.Finalize;
end Parser_Transformer;
