description = "FastCGI implementation (demo)"
name = "matreshka_fastcgi"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_fastcgi.gpr"]
tags = ["web", "cgi", "http"]

[configuration]
disabled = true

[[depends-on]]
matreshka_league = "22.0.0"

