description = "Web-application server. API library"
name = "matreshka_spikedog_awsd"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
executables = ["spikedog_awsd"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_spikedog_awsd.gpr"]
tags = ["web", "servlet"]

[configuration]
disabled = true

[[depends-on]]
aws = "any"
matreshka_league = "22.0.0"
matreshka_spikedog_core = "22.0.0"

[gpr-set-externals]
LIBRARY_TYPE="relocatable"

