description = "Firebird SQL binding for Ada"
name = "matreshka_sql_firebird"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_sql_firebird.gpr"]
tags = ["sql", "database", "db", "firebird"]

[configuration]
disabled = true

[[depends-on]]
libfbclient = "any"
matreshka_league = "22.0.0"
matreshka_sql = "22.0.0"

