description = "Library to manipulate with XML streams and documents"
name = "matreshka_xml"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_xml.gpr"]
tags = ["xml", "dom", "catalog", "templates", "html5"]

[configuration]
disabled = true

[[depends-on]]
matreshka_league = "22.0.0"

