------------------------------------------------------------------------------
--                                                                          --
--                            Matreshka Project                             --
--                                                                          --
--         Localization, Internationalization, Globalization for Ada        --
--                                                                          --
--                              Tools Component                             --
--                                                                          --
------------------------------------------------------------------------------
--                                                                          --
-- Copyright © 2010 Vadim Godunko <vgodunko@gmail.com>                      --
--                                                                          --
-- Matreshka is free software;  you can  redistribute it  and/or modify  it --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software  Foundation;  either version 2,  or (at your option)  any later --
-- version.  Matreshka  is distributed in the hope that it will be  useful, --
-- but   WITHOUT  ANY  WARRANTY;  without  even  the  implied  warranty  of --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General --
-- Public License for more details.  You should have received a copy of the --
-- GNU General Public License distributed with Matreshka; see file COPYING. --
-- If not, write  to  the  Free Software Foundation,  51  Franklin  Street, --
-- Fifth Floor, Boston, MA 02110-1301, USA.                                 --
--                                                                          --
------------------------------------------------------------------------------
--  $Revision$ $Date$
------------------------------------------------------------------------------
--  This program extracts data from the code generated by aflex, and generate
--  actual implementation of scanner for regular expression engine.

with Ada.Characters.Conversions;
with Ada.Command_Line;
with Asis.Ada_Environments;
with Asis.Compilation_Units;
with Asis.Elements;
with Asis.Implementation;

with Scanner_Extractor;
with Scanner_Generator;

procedure Scanner_Transformer is
   Transformer_Context : Asis.Context;
   Scanner_Unit        : Asis.Compilation_Unit;
   Scanner_Body        : Asis.Element;

begin
   Asis.Implementation.Initialize ("-asis05");
   Asis.Ada_Environments.Associate
    (Transformer_Context,
     "Transformer_Context",
     "-C1 "
       & Ada.Characters.Conversions.To_Wide_String
          (Ada.Command_Line.Argument (2)));
   Asis.Ada_Environments.Open (Transformer_Context);

   if Ada.Command_Line.Argument (1) = "regexp" then
      Scanner_Unit :=
        Asis.Compilation_Units.Compilation_Unit_Body
         ("Regexp_Scanner", Transformer_Context);
      Scanner_Body := Asis.Elements.Unit_Declaration (Scanner_Unit);

   elsif Ada.Command_Line.Argument (1) = "xml" then
      Scanner_Unit :=
        Asis.Compilation_Units.Compilation_Unit_Body
         ("Xml_Scanner", Transformer_Context);
      Scanner_Body := Asis.Elements.Unit_Declaration (Scanner_Unit);
   end if;

   Scanner_Extractor.Extract (Scanner_Body);
   Scanner_Generator.Generate_Scanner_Code;
   Scanner_Generator.Generate_Scanner_Tables;

   Asis.Ada_Environments.Close (Transformer_Context);
   Asis.Ada_Environments.Dissociate (Transformer_Context);
   Asis.Implementation.Finalize;
end Scanner_Transformer;
