description = "Web-application server. Implementation library"
name = "matreshka_spikedog_core"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_spikedog_core.gpr"]
tags = ["web", "servlet"]

[configuration]
disabled = true

[[depends-on]]
matreshka_league = "22.0.0"
matreshka_spikedog_api = "22.0.0"

