description = "WS-Security 1.1 implementation for SOAP 1.2"
name = "matreshka_soap_wsse"
version = "22.0.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["../../../gnat/matreshka_soap_wsse.gpr"]
tags = ["soap", "wsse", "web"]

[configuration]
disabled = true

[[depends-on]]
matreshka_league = "22.0.0"
matreshka_soap = "22.0.0"

